# Generated by Django 5.1 on 2024-09-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='place_id',
            field=models.CharField(default='default_place_id', max_length=255, unique=True),
        ),
    ]
